package com.xiu.search.dao.model;

import java.io.Serializable;
import java.util.Date;

public class XDataBrand implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3646006535650192355L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.BRAND_ID
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.BRAND_CODE
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String brandCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.BRAND_NAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.EN_NAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String enName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.MAIN_NAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String mainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.NAME_FLAG
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private Long nameFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.SHOW_FLAG
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private Long showFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.DELETE_FLAG
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private Long deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.COMPANYNAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.STORY
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String story;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.COUNTRY
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.OFFICIALURL
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String officialurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.DESCRIPTION
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.BANNERURL
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String bannerurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.BANNERIMGNAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String bannerimgname;
    
    /**
     * add by dingchenghong - 20140416
     * brand第二张brand图片
     */
    private String bannerimgname2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.AUTHIMGURL
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String authimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.AUTHIMGNAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String authimgname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.STOREIMGURL
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String storeimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.STOREIMGNAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private String storeimgname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.STORE_ID
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.CREATE_TIME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XIU_GOODS.X_DATA_BRAND.UPDATE_TIME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    private Date updateTime;
    
    private Integer orgauthFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.BRAND_ID
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.BRAND_ID
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.BRAND_ID
     *
     * @param brandId the value for XIU_GOODS.X_DATA_BRAND.BRAND_ID
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.BRAND_CODE
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.BRAND_CODE
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getBrandCode() {
        return brandCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.BRAND_CODE
     *
     * @param brandCode the value for XIU_GOODS.X_DATA_BRAND.BRAND_CODE
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setBrandCode(String brandCode) {
        this.brandCode = brandCode == null ? null : brandCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.BRAND_NAME
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.BRAND_NAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.BRAND_NAME
     *
     * @param brandName the value for XIU_GOODS.X_DATA_BRAND.BRAND_NAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.EN_NAME
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.EN_NAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.EN_NAME
     *
     * @param enName the value for XIU_GOODS.X_DATA_BRAND.EN_NAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.MAIN_NAME
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.MAIN_NAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getMainName() {
        return mainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.MAIN_NAME
     *
     * @param mainName the value for XIU_GOODS.X_DATA_BRAND.MAIN_NAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setMainName(String mainName) {
        this.mainName = mainName == null ? null : mainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.NAME_FLAG
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.NAME_FLAG
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public Long getNameFlag() {
        return nameFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.NAME_FLAG
     *
     * @param nameFlag the value for XIU_GOODS.X_DATA_BRAND.NAME_FLAG
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setNameFlag(Long nameFlag) {
        this.nameFlag = nameFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.SHOW_FLAG
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.SHOW_FLAG
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public Long getShowFlag() {
        return showFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.SHOW_FLAG
     *
     * @param showFlag the value for XIU_GOODS.X_DATA_BRAND.SHOW_FLAG
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setShowFlag(Long showFlag) {
        this.showFlag = showFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.DELETE_FLAG
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.DELETE_FLAG
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public Long getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.DELETE_FLAG
     *
     * @param deleteFlag the value for XIU_GOODS.X_DATA_BRAND.DELETE_FLAG
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setDeleteFlag(Long deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.COMPANYNAME
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.COMPANYNAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.COMPANYNAME
     *
     * @param companyname the value for XIU_GOODS.X_DATA_BRAND.COMPANYNAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.STORY
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.STORY
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getStory() {
        return story;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.STORY
     *
     * @param story the value for XIU_GOODS.X_DATA_BRAND.STORY
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setStory(String story) {
        this.story = story == null ? null : story.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.COUNTRY
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.COUNTRY
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.COUNTRY
     *
     * @param country the value for XIU_GOODS.X_DATA_BRAND.COUNTRY
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.OFFICIALURL
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.OFFICIALURL
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getOfficialurl() {
        return officialurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.OFFICIALURL
     *
     * @param officialurl the value for XIU_GOODS.X_DATA_BRAND.OFFICIALURL
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setOfficialurl(String officialurl) {
        this.officialurl = officialurl == null ? null : officialurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.DESCRIPTION
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.DESCRIPTION
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.DESCRIPTION
     *
     * @param description the value for XIU_GOODS.X_DATA_BRAND.DESCRIPTION
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.BANNERURL
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.BANNERURL
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getBannerurl() {
        return bannerurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.BANNERURL
     *
     * @param bannerurl the value for XIU_GOODS.X_DATA_BRAND.BANNERURL
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setBannerurl(String bannerurl) {
        this.bannerurl = bannerurl == null ? null : bannerurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.BANNERIMGNAME
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.BANNERIMGNAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getBannerimgname() {
        return bannerimgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.BANNERIMGNAME
     *
     * @param bannerimgname the value for XIU_GOODS.X_DATA_BRAND.BANNERIMGNAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setBannerimgname(String bannerimgname) {
        this.bannerimgname = bannerimgname == null ? null : bannerimgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.AUTHIMGURL
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.AUTHIMGURL
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getAuthimgurl() {
        return authimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.AUTHIMGURL
     *
     * @param authimgurl the value for XIU_GOODS.X_DATA_BRAND.AUTHIMGURL
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setAuthimgurl(String authimgurl) {
        this.authimgurl = authimgurl == null ? null : authimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.AUTHIMGNAME
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.AUTHIMGNAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getAuthimgname() {
        return authimgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.AUTHIMGNAME
     *
     * @param authimgname the value for XIU_GOODS.X_DATA_BRAND.AUTHIMGNAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setAuthimgname(String authimgname) {
        this.authimgname = authimgname == null ? null : authimgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.STOREIMGURL
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.STOREIMGURL
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getStoreimgurl() {
        return storeimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.STOREIMGURL
     *
     * @param storeimgurl the value for XIU_GOODS.X_DATA_BRAND.STOREIMGURL
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setStoreimgurl(String storeimgurl) {
        this.storeimgurl = storeimgurl == null ? null : storeimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.STOREIMGNAME
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.STOREIMGNAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public String getStoreimgname() {
        return storeimgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.STOREIMGNAME
     *
     * @param storeimgname the value for XIU_GOODS.X_DATA_BRAND.STOREIMGNAME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setStoreimgname(String storeimgname) {
        this.storeimgname = storeimgname == null ? null : storeimgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.STORE_ID
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.STORE_ID
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.STORE_ID
     *
     * @param storeId the value for XIU_GOODS.X_DATA_BRAND.STORE_ID
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.CREATE_TIME
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.CREATE_TIME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.CREATE_TIME
     *
     * @param createTime the value for XIU_GOODS.X_DATA_BRAND.CREATE_TIME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XIU_GOODS.X_DATA_BRAND.UPDATE_TIME
     *
     * @return the value of XIU_GOODS.X_DATA_BRAND.UPDATE_TIME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XIU_GOODS.X_DATA_BRAND.UPDATE_TIME
     *
     * @param updateTime the value for XIU_GOODS.X_DATA_BRAND.UPDATE_TIME
     *
     * @mbggenerated Tue Jul 17 10:47:54 CST 2012
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public Integer getOrgauthFlag() {
		return orgauthFlag;
	}

	public void setOrgauthFlag(Integer orgauthFlag) {
		this.orgauthFlag = orgauthFlag;
	}
	
	
	
	public String getBannerimgname2() {
		return bannerimgname2;
	}

	public void setBannerimgname2(String bannerimgname2) {
		this.bannerimgname2 = bannerimgname2;
	}



	public transient static final XDataBrand EMPTY_OBJECT = new XDataBrand();
	
}