package com.xiu.search.dao.model;

import java.io.Serializable;
import java.util.Date;

public class XiuSearchConfigModel implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XIU_SEARCH_CONFIG.CONFIG_ID
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    private Long configId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XIU_SEARCH_CONFIG.CONFIG_GROUPNAME
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    private String configGroupname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XIU_SEARCH_CONFIG.CONFIG_STATUS
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    private String configStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XIU_SEARCH_CONFIG.CONFIG_KEY
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    private String configKey;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XIU_SEARCH_CONFIG.CONFIG_VALUE
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    private String configValue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XIU_SEARCH_CONFIG.CONFIG_UPDATETIME
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    private Date configUpdatetime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XIU_SEARCH_CONFIG.CONFIG_DESC
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    private String configDesc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table XIU_SEARCH_CONFIG
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XIU_SEARCH_CONFIG.CONFIG_ID
     *
     * @return the value of XIU_SEARCH_CONFIG.CONFIG_ID
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public Long getConfigId() {
        return configId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XIU_SEARCH_CONFIG.CONFIG_ID
     *
     * @param configId the value for XIU_SEARCH_CONFIG.CONFIG_ID
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XIU_SEARCH_CONFIG.CONFIG_GROUPNAME
     *
     * @return the value of XIU_SEARCH_CONFIG.CONFIG_GROUPNAME
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public String getConfigGroupname() {
        return configGroupname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XIU_SEARCH_CONFIG.CONFIG_GROUPNAME
     *
     * @param configGroupname the value for XIU_SEARCH_CONFIG.CONFIG_GROUPNAME
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public void setConfigGroupname(String configGroupname) {
        this.configGroupname = configGroupname == null ? null : configGroupname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XIU_SEARCH_CONFIG.CONFIG_STATUS
     *
     * @return the value of XIU_SEARCH_CONFIG.CONFIG_STATUS
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public String getConfigStatus() {
        return configStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XIU_SEARCH_CONFIG.CONFIG_STATUS
     *
     * @param configStatus the value for XIU_SEARCH_CONFIG.CONFIG_STATUS
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public void setConfigStatus(String configStatus) {
        this.configStatus = configStatus == null ? null : configStatus.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XIU_SEARCH_CONFIG.CONFIG_KEY
     *
     * @return the value of XIU_SEARCH_CONFIG.CONFIG_KEY
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XIU_SEARCH_CONFIG.CONFIG_KEY
     *
     * @param configKey the value for XIU_SEARCH_CONFIG.CONFIG_KEY
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XIU_SEARCH_CONFIG.CONFIG_VALUE
     *
     * @return the value of XIU_SEARCH_CONFIG.CONFIG_VALUE
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XIU_SEARCH_CONFIG.CONFIG_VALUE
     *
     * @param configValue the value for XIU_SEARCH_CONFIG.CONFIG_VALUE
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XIU_SEARCH_CONFIG.CONFIG_UPDATETIME
     *
     * @return the value of XIU_SEARCH_CONFIG.CONFIG_UPDATETIME
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public Date getConfigUpdatetime() {
        return configUpdatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XIU_SEARCH_CONFIG.CONFIG_UPDATETIME
     *
     * @param configUpdatetime the value for XIU_SEARCH_CONFIG.CONFIG_UPDATETIME
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public void setConfigUpdatetime(Date configUpdatetime) {
        this.configUpdatetime = configUpdatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XIU_SEARCH_CONFIG.CONFIG_DESC
     *
     * @return the value of XIU_SEARCH_CONFIG.CONFIG_DESC
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public String getConfigDesc() {
        return configDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XIU_SEARCH_CONFIG.CONFIG_DESC
     *
     * @param configDesc the value for XIU_SEARCH_CONFIG.CONFIG_DESC
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    public void setConfigDesc(String configDesc) {
        this.configDesc = configDesc == null ? null : configDesc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table XIU_SEARCH_CONFIG
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof XiuSearchConfigModel)) {
            return false;
        }
        XiuSearchConfigModel other = (XiuSearchConfigModel) that;
        return this.getConfigId() == null ? other == null : this.getConfigId().equals(other.getConfigId())
            && this.getConfigGroupname() == null ? other == null : this.getConfigGroupname().equals(other.getConfigGroupname())
            && this.getConfigStatus() == null ? other == null : this.getConfigStatus().equals(other.getConfigStatus())
            && this.getConfigKey() == null ? other == null : this.getConfigKey().equals(other.getConfigKey())
            && this.getConfigValue() == null ? other == null : this.getConfigValue().equals(other.getConfigValue())
            && this.getConfigUpdatetime() == null ? other == null : this.getConfigUpdatetime().equals(other.getConfigUpdatetime())
            && this.getConfigDesc() == null ? other == null : this.getConfigDesc().equals(other.getConfigDesc());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table XIU_SEARCH_CONFIG
     *
     * @ibatorgenerated Fri May 10 16:30:40 CST 2013
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getConfigId() != null) {
            hash *= getConfigId().hashCode();
        }
        if (getConfigGroupname() != null) {
            hash *= getConfigGroupname().hashCode();
        }
        if (getConfigStatus() != null) {
            hash *= getConfigStatus().hashCode();
        }
        if (getConfigKey() != null) {
            hash *= getConfigKey().hashCode();
        }
        if (getConfigValue() != null) {
            hash *= getConfigValue().hashCode();
        }
        if (getConfigUpdatetime() != null) {
            hash *= getConfigUpdatetime().hashCode();
        }
        if (getConfigDesc() != null) {
            hash *= getConfigDesc().hashCode();
        }
        return hash;
    }
}